#
# Development compose file. Do not use this when deploying
# to a production environment.
#

version: "3.1"
services:

  webserver:
    build: docker/webserver
    container_name: ssls-webserver
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html

      # Apache
      - ./storage/logs/apache:/var/log/apache2
      - ./docker/webserver/apache/apache2.conf:/etc/apache2/apache2.conf
      - ./docker/webserver/apache/sites-enabled/000-default.conf:/etc/apache2/sites-enabled/000-default.conf

      # PHP
      - ./docker/webserver/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/webserver/php/conf.d/zz-php-development.ini:/usr/local/etc/php/conf.d/zz-php-development.ini
