#
# Development compose file. Do not use this when deploying
# to a production environment.
#

version: "3.1"
services:

  db:
    image: mariadb:10.5.9
    restart: always
    container_name: ssls-db
    working_dir: /application
    volumes:
      - ./docker/mariadb/init/01-databases.sql:/docker-entrypoint-initdb.d/01-databases.sql
      - .:/application
      - ./docker/mariadb/conf.d:/etc/mysql/conf.d/
      - ./docker/mariadb/data:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        MYSQL_DATABASE: '${DB_DATABASE}'
        MYSQL_USER: '${DB_USERNAME}'
        MYSQL_PASSWORD: '${DB_PASSWORD}'
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3306:3306"

  webserver:
    build: docker/webserver
    container_name: ssls-webserver
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html

      # Apache
      - ./storage/logs/apache:/var/log/apache2
      - ./docker/webserver/apache/apache2.conf:/etc/apache2/apache2.conf
      - ./docker/webserver/apache/sites-enabled/000-default.conf:/etc/apache2/sites-enabled/000-default.conf

      # PHP
      - ./docker/webserver/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/webserver/php/conf.d/zz-php-development.ini:/usr/local/etc/php/conf.d/zz-php-development.ini

  elasticsearch:
    image: elasticsearch:7.11.1
    container_name: ssls-elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
    ports:
      - 9200:9200
    volumes:
      - ./docker/elasticsearch/data:/usr/share/elasticsearch/data

  kibana:
    image: kibana:7.11.1
    container_name: ssls-kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - 5601:5601
